import type { Metadata } from "next";
import { geist } from '../fonts';
import "./globals.css";




export const metadata: Metadata = {
  title: "Time 4 school",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geist.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
 